### ISSUE TITLE
Task: brainstorm enemy mechanics

### ISSUE THREAD

**Issue by SophieH8** [Allen-ISD-Computer-Science/REPO_Platformer2D_2024#65]

**Comment by EighthRisen** [comment]
1. Basic enemy that can only walk at you within certain distance.
2. Shoots small slow projectiles.
3. Faster projectiles.
4. Deflecting projectiles?
5. Breakable projectiles?
(there are many different ways to make ranged enemies, curved arcs, boomerangs etc, explosives etc)
7. Blocking enemies (temporarily invincible)
8. Flying enemies 
9. Enemies with a charge attack (runs fast at you pauses then runs fast again)
10.  Flying enemies with a charge
11. Flying enemies with projectiles
12. Enemies that multiply into smaller version of themselves (like a Minecraft slime) as you kill them until a certain amount of times.
13. Enemies that spawn more tiny enemies until main enemy is slain.
14.  Creeper type enemy? (kaboom)
15.  Small teleports (seems hard)
16. Enemies that jump high and try to land on you
17. Long melee attack timers you have to wait to end before you can attack
18.  Spellcasters (multiple different projectiles or even like can spawn something to drop over you?) Can discuss because spellcasting is broad.
19. Boss enemy has a mix of most or all other mechanics
20. Comment other types if you have an idea!
